### PR TITLE
Added Kotlin Support

### PR DESCRIPTION
**Pull request by JesseScott**
Enabled as per https://github.com/PrismJS/prism/pull/814/files

### CODE REVIEW

**Comment by reyronald** [comment]
Hi @JesseScott !

Did you test if it works with the current version of Prism that we are using currently in the extension?

**Comment by JesseScott** [comment]
I didn't test locally (_i guess this would involve creating the crx file and loading the 'unsafe' (unsigned) extension locally ???_)... i tried to see if there were development/contributing/testing steps in a Wiki for example, but can't see any in this repo - are there any that I missed ? (_would be a great follow-up PR!_)

but... the PR I linked above was merged in 2015, so i imagine that we are using a more recent version! (_at least, i hope so!_)

also, I *DO* see Kotlin in the `prism.js` file at https://github.com/andremw/refined-bitbucket/blob/dev/extension/prism.js but am unsure where the current version is being annotated... do you know ?

**Comment by reyronald** [comment]
@JesseScott  Fair enough, I can test it locally for you just to be sure, do you by any chance have a link to a public Bitbucket PR with Kotlin code in it?

**Comment by JesseScott** [comment]
Hmm, no, just private ones. I can do this tomorrow though!

**Comment by JesseScott** [comment]
@reyronald 

Public BitBucket PR: 

https://bitbucket.org/JesseColinScott/kotlin-extensions/overview

**Comment by reyronald** [comment]
@JesseScott I see no PRs in the repo, can you create one?

**Comment by JesseScott** [comment]
Ah, thought this would work on just source too, not just PRs... hold on!

**Comment by JesseScott** [comment]
https://bitbucket.org/JesseColinScott/kotlin-extensions/pull-requests/1/added-intasboolean-and-booleanasint/diff

**Comment by reyronald** [comment]
Hello @JesseScott ,

Sorry for having you go through all of those hurdles! 

I tested it and seems to be working fine, I'm gonna go ahead and merge it and include it in the next release, thank you for the contribution!

**Comment by JesseScott** [comment]
No need to apologize, that's what PRs are for!
Also, I should have properly dev tested it myself!
Still need a local dev section of the Wiki...

**Pull request merged**
