### PR TITLE
Includes C# cshtml as a language-markup

### PR DESCRIPTION
**Pull request by renatoch**

### CODE REVIEW

**Comment by renatoch** [comment]
I also wanted to add @* and *@ to the block comment highlighting, but wasn't sure modifying the original language-markup syntax in prism.js was the way to go.
Any tips?

**Comment by andremw** [comment]
Hi, @renatoch . Thanks for your contribution!

I've never extended prism, but I think this link might help you: http://asarosenberg.se/code/extending-and-customizing-prism-syntax-highlighter/

**Comment by renatoch** [comment]
Ok @andremw , thanks! I'll have a look later.

I tried to install the updated package in chrome store, but getting error in image. Any clues?

refined bitbucket - chrome web store - google chrome

**Comment by andremw** [comment]
Sorry, @renatoch. What happened was that I simply forgot the options.html file. It's been some time since the last package upload.. Think I gotta automate this.. :thinking: 

Thanks for reporting!

**Comment by renatoch** [comment]
Thanks, working now! =)

**Pull request merged**
