### PR TITLE
feat(autocollapse): Autocollapse feature

### PR DESCRIPTION
**Pull request by reyronald**
Add file patterns in the Options page that you would like the extension to collapse automatically when the Pull Request loads.

autocollapse

### CODE REVIEW

**Comment by apitzele** [comment]
I tried this out today.  It's great and definitely plugs another hole with BB.  Thanks!

**Comment by reyronald** [comment]
Hey @apitzele , that's awesome! Thank you for taking the time to come and letting me now! Definitely helps to keep the motivation up.

I am currently working on two new features before deploying all of this into a new published release that I've been needing myself, one is a "pullrequest ignore", which is basically the same as this one, but instead of just collapsing, it completely removes the diff from the page.

The other one is a "load all unloaded diffs" button somewhere on top of the pull request view. When the PR is too large, Bitbucket stops loading the diffs for all files above a certain amount. I find myself sometimes wanting to do a Ctrl+F to check for specific changes when I'm reviewing code but can't rely on it because of all the unloaded diffs.

Anyway, I'm rolling them out in the course of the week. If you find any weird behavior or bugs, or have an idea for any new feature that could be useful, let me know!

**Comment by apitzele** [comment]
Those both feel like useful features (especially the "load all unloaded diffs").  When there are 50+ files that don't load, it's very tedious to manually load all of them.  Great idea!

A feature we could add which would have a pretty significant impact (at least for me) is syntax highlighting for modified lines on the unified diff.   I implemented the side by side diff highlighting and I don't find it to be distracting on modified lines.  I'm not sure if ignoring the modified lines was intentional. This may have been working at some point (I just don't remember) so it's possible the BB UI refresh broke it.  
Any thoughts on this?  I'd be happy to log an issue and submit a PR for it.

Thanks again for taking time to work on this.  Many of the developers at my office use the extension.

**Comment by reyronald** [comment]
@apitzele I believe you are referring to issue #63 ? If that's the one you mean I don't think it was intentional, probably an edge case that wasn't taken into account when implemented initially.

 I was going to tackle that issue after finishing with the features I mentioned, but if you have time to take a look at it it would be great!

**Comment by apitzele** [comment]
Sure, I'll take a look at it tonight.  I didn't see there was a ticket already added.

**Pull request merged**
