### PR TITLE
fix(#41): Apply syntax highlighting to diffs loaded on user demand when PR is too big.

### PR DESCRIPTION
**Pull request by reyronald**
A few things to highlight about the PR:

- The classic for loop inside the new `MutationObserver` is intentional. Although unquestionably uglier, is it orders of magnitude more performant than using the functional approach, specially inside the observer callback, which may fire multiple times per second.
- I modified the `'highlight'` event flow so that it receives the container it is supposed to operate on. Before, everytime the '`highlight'` event was fired (which was every time the user requested to load more lines of code of any diff), the extension would run through the whole document, going through nodes of already processed containers. For very large PRs, this is definitely noticeable.
- I modified the `transformPreElements()` function so that it only wraps the contents of the `<pre>` tags in `<code>` tags when it has no child nodes (in other words, when it only has text). Before, I noticed that sometimes the source lines would end up with a `<pre><code><code><code>...`  structure.
- Bitbucket has a predefined timeout for the PR page to load that's above 2.5 seconds. When it takes more time beyond that timeout, it renders all the diffs it has available at the moment and the remaining ones are loaded when user demands with the "Click here to try again" link. I increased the timeout constant of the `waitForRender` method to be above Bitbucket's limit, that way, as of the current Bitbucket's implementation, no PR will ever load with unhighlighted text, which was the case when it took more than 2.5 seconds before.

I tried to include as little code as possible to fix this issue, while messing the least I could with the structure and any previously existing code. That said, I did notice a few bottlenecks and performance improvements that could be made. I deal with very large PRs in my work environment on a regular basis (hundreds of files, tens of thousands of diff lines) and in those cases the poor performance becomes a little noticeable. If any other user brings it up or there's interest, I'm willing to be part of the effort to improve it.

Before
before

After
after

### CODE REVIEW

**Comment by andremw** [comment]
Thanks a lot, @reyronald. It's definitely a great improvement.

Regarding the other performance issues I agree with you (and I'm asking myself why I haven't at least opened an issue for it). I think we could use Prism's web worker feature, or maybe limit the highlight to N px below and above the viewport. This way we would only highlight "on scroll".

As you've probably noticed, I haven't found much time to maintain the repo in the last months, and now I stopped using BitBucket. So I'm looking for people that wants to maintain it.
I've already talked to @rproenca to see if he'll be able to maintain it and if he can gather more people to join.

If you want, I can give you collaborator access for now so that you can contribute more freely.

**Comment by reyronald** [comment]
Hello @andremw ,

I'm glad to hear you found my contribution useful!

I still use BitBucket everyday at my full-time job and would certainly be up for maintaining / contributing to it in the long run. There is in fact another feature to the extension that I was planning to contribute in the following weeks if I managed to get a hold of you (hiding diffs for specific file extensions, more on that later).

For this specific issue I didn't have to look into Prism's documentation much because everything I needed was already there, but those approaches you mention sure sound like possible improvements. If you have any other ideas and the time to put them up as issues, I can look into them later. After all I'll be benefiting from it.

Let me know if you have any comments on the PR. If we can merge this I would be suggesting my team to install the extension too, hehe.

**Comment by andremw** [comment]
It's ok. I'll merge it and update the extension. I'll let you know as soon as I publish a new version of the extension (today).

**Comment by andremw** [comment]
@reyronald I just published it and it'll be available in some minutes.

**Comment by reyronald** [comment]
I tried to update it but this happened, is it anything related with the code I added?

capture

**Comment by andremw** [comment]
I'm sorry, that was my mistake. I forgot to include these files in the zip file. I should automate (or at least document ¬¬) it, because after some time I forget how to create the package.
@reyronald just published it. Let's see if it works now.

**Comment by reyronald** [comment]
Just updated it and works great! Thanks @andremw !

**Pull request merged**
