### PR TITLE
New Features: Updates Syntax Highlighting To Work On New PR UI, And Adds Theme Support For All Syntax Highlighting

### PR DESCRIPTION
**Pull request by RobertChrist**
-   [ ] I updated the CHANGELOG.md
-   [x] I tested the changes in this pull request myself
-   [x] I added Automated Tests
-   [x] I added an Option to enable / disable this feature
-   [x] I updated the README.md, with pictures if necessary

---
This PR accomplishes two things.

Firstly, it brings syntax highlighting to the new PR UI, as discussed in issue 376 (https://github.com/refined-bitbucket/refined-bitbucket/issues/376).  I based my changes off of the current old-ui syntax highlighting code (which has been left almost completely unchanged), and the greasemonkey script referenced in that issue.  I additionally made improvements to the greasemonkey script, and finally, I modified the script so it now does not override bitbucket's native word-level highlighting in PRs.

The second change implemented here is the introduction of prism.js theme support to the plugin.  In the option menu, all 8 default prism.js themes are now available.  All themes have been tested, and work in both the new and old PR UIs.

### CODE REVIEW

**Comment by reyronald** [comment]
hey @andremw I have visibility on everything that happens in this repo so you don't have to explicitly request my review on pull requests, its not needed and clutters my email inbox and notifications 😅

**Comment by andremw** [comment]
@reyronald we talk about this in the e-mail.

Regards,

**Comment by andremw** [comment]
@reyronald, I understand.

We talk more about this in the e-mail.

Regards,

**Review by reyronald — APPROVED** [review]
Thank you for taking this on Robert, great job!

Glad the original syntax highlighting code for the old UI worked for the most part.

**Comment by RobertChrist** [comment]
w0000000!  Thank you @reyronald!  Happy to have helped!

**Pull request merged**
