### PR TITLE
Support .c and .d extensions

### PR DESCRIPTION
**Pull request by EyalIO**
*   [ ] I updated the CHANGELOG.md
*   [x] I tested the changes in this pull request myself
*   [ ] I added Automated Tests
*   [ ] I added an Option to enable / disable this feature
*   [ ] I updated the README.md, with pictures if necessary

---

### CODE REVIEW

**Comment by reyronald** [comment]
Hello @EyalIO , both C and D are already for a while in the extension, these changes shouldn't be necessary, if it wasn't working for you it must've been for some other reason, let me know so that we can work through it.

**Comment by EyalIO** [comment]
What handles the .c or .d extensions? Is there a different mechanism besides this file?

I thought it didn't work -- but now it seems that it does work without these changes.

**Comment by reyronald** [comment]
@EyalIO Yeah, there's an explanation for it in the comments at the top of the file. Basically if the extension directly matches the name of the class, then it is handled automatically (i.e. `.c` -> `language-c`, `.d` -> `language-d`, etc.)

**Comment by EyalIO** [comment]
Ah, I see, thanks!

**Pull request closed without merging**
