### PR TITLE
added side-by-side view syntax highlighting

### PR DESCRIPTION
**Pull request by apitzele**
I added the side-by-side diff support.  Where applicable I used the functions you've already written to accomplish this.  I also included a few minor changes but I have no problem reverting them if you do not wish to pull them in.

There are a number of .NET specific file extensions that would benefit from syntax highlighting support (my organization is largely a .NET shop) . I also added .sql support since Prism.js supports it out of the box.

While debugging, I noticed a JavaScript error occurs when the merge button is not displayed for merged PRs so I put a check around it

I removed the case sensitivity for extension/language resolution.  Since Windows is somewhat wonky the way it preserves case, it would make things smoother on the Windows side if the language check is not case sensitive.  If you feel differently, I will remove the this change.
##### One Suggestion:

I noticed that the build npm browserfiy build task has a wild card in the command.  Unfortunately, after a bit of Googling, it would seem this is not platform agnostic i.e. (it breaks in Windows). I would suggest mentioning this in the readme if you decide to keep the wildcard and continue to accept community contributions.

### CODE REVIEW

**Comment by andremw** [comment]
Thanks for you PR, @apitzele.
I think that this was the feature that the extension was missing the most so far. It will be really helpful.

No problem doing these minor changes, and the new file extensions are great!

I reviewed the code and found just a few things we could change: 
One is the global $ that xo is not recognizing (you can see it in travis-ci link above). To make xo stop complaining you can declare the global property either in package.json or using that /\* global $ */ in the events.js file. But you can instead replace the jQuery code with Array.from(document.qsa...) like you're doing in the functions you created in syntax-highlight.js. I think that this approach would be nice to keep a standard. I don't dislike jQuery, but since events.js doesn't really need jQuery so far, I think it's a good thing to keep it out just to maintain a code "pattern".
The other thing I would change is replacing var and string concatenation in the new code you wrote in syntax-highlight.js with ES6 features. You didn't notice this because in package.json I forgot to update the test script to also check "src/*_/_.js".

I also noticed this debounced diff handler thing and I wonder if we could apply it to our normal screen diff highlighting as well. I think this lazy-highlighting would improve performance **a lot** in cases where we have tons of large files (the extension normally freezes the screen for some time here). This is something I thought about a long time ago but didn't manage to fix.

I noticed a thing in the debounced function though, that hinders performance a little bit. This reference to the arguments parameter. You can read about it [here](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments). But here it's not something I'm worried about. Just wanted to share this knowledge with you. Might be useful somewhere else.

Regarding your suggestion, I didn't know that wildcards don't work in Windows. How did you overcome this issue? I haven't come up with a solution for this yet.. What do you think we can do here?

Anyway, I think this PR is amazing! I'm really glad you took some time to work on that (and this debounced stuff is so cool). Thank you _very much_!

**Comment by apitzele** [comment]
Thanks for the feedback.  I'll look at replacing those jQuery instances tonight and will update PR with your suggestions.

I can also take a look at using debounce elsewhere but it might make make more sense to use a throttle.  When the PR overview screen loads the diff hunks for all files are loaded at once (but only once so we'd probably not gain anything from debouncing that operation).  Throttling the load might be useful though since there are screen freezes.

Regarding the build run,  I simply ran the command by listing out every file.  Yuck!  I even tried running it from a bash shell but got the same error.
There was a browserify ticket that was closed as a won't fix since it is a Windows problem.
https://github.com/substack/node-browserify/issues/1170
I suppose a separate command with Windows wildcards should work.  Two build commands would be preferable to maintaining the list of files in the json package.

**Comment by andremw** [comment]
Nice. We can do this analysis and implementation of throttling in another task.
Regarding the build run, I think we can use this lib [here](https://github.com/isaacs/node-glob) as a dev-dependency to use these wildcards in all OS while having one build command. What do you think?

**Comment by apitzele** [comment]
Thanks for pulling that in so quickly.  In regards to glob, I read through their readme and it seems like it may be just what we need.  I'll try and prove it out in Windows.

**Comment by reyronald** [comment]
@apitzele @andremw Any advances with the globs for Windows? I wanted to debug some things to see if I could contribute but ran into the same issue with the build. Have any of you looked into it so far?

**Pull request merged**
