### PR TITLE
Added double-click word selection feature

### PR DESCRIPTION
**Pull request by rproenca**
There are two kown issues. Please see commit comments.
I also added chrome extension icons

### CODE REVIEW

**Comment by andremw** [comment]
I will not merge the PR because I think we can do it in another repo. It would be fun to have another project to play with. So let's create it and work there.
But anyway, I think we can avoid using external libs for now. Just to check how hard it is to create such a lib and to make it lighter.

**Comment by andremw-cit** [comment]
Let's use this solution. But I think jQuery is an unnecessary dependency, as we have options that are lighter.

**Comment by andremw** [comment]
Let's use this solution. But I think jQuery is an unnecessary dependency, as we have options that are lighter.

**Comment by rproenca** [comment]
Andre, please upload the package again to chrome store.
Just a tip: I think the version number is increasing very quick. I would say this is version 0.2.0 and not 2.0 ;)

**Comment by andremw** [comment]
I also think it's too fast. But now we cannot decrease the version in the webstore. So I'll check what I'm doing wrong in updating these versions and try to slow down.

Also, remember to update the readme.md to include this new feature.

**Pull request merged**
