### PR TITLE
Highlighting: Add .php

### PR DESCRIPTION
**Pull request by GaryJones**
Adds recognition of `.php` extension.

### CODE REVIEW

**Comment by reyronald** [comment]
Hello @GaryJones , it's not necessary to add languages whose alias match exactly the name of the file extension. 

Isn't your extension highlighting your .php files?

**Comment by GaryJones** [comment]
> Isn't your extension highlighting your .php files?

Some files do:

screenshot 2018-02-15 10 30 29

Some files don't:

screenshot 2018-02-15 10 30 46

The one I looked at before doing the PR was apparently one that didn't.

**Comment by reyronald** [comment]
@GaryJones Apparently there's a bug in the most recent release that causes some files to not be highlighted, another user reported this to me too in #151 :(

I haven't yet experience this myself so I've been able to solve it, are you seeing errors in the developer console of your browser?

**Comment by GaryJones** [comment]
> are you seeing errors in the developer console of your browser?

There's a couple of deprecation warnings (and a block of a NewRelic script presumably from BB), but nothing obviously related to highlighting or JS error.

Interestingly, one of the files I posted the screenshot of earlier showing the highlighting, is now missing the highlighting as well:

screenshot 2018-02-15 20 29 56

I'm not sure what's changed.

**Comment by reyronald** [comment]
Those deprecation warnings are from Bitbucket.org itself, not from the extension.

For those diff sections that highlighting doesn't work, do they have the toggle diff button to the right? Also, if you click the "Show more lines" button, are the newly loaded lines highlighted?

If there are no errors in the console, I think the only possible clue we could get is by debugging the issue, but until I don't bump into this bug myself I'm not going to be able to do it :(, are you using Chrome or Firefox by the way? I don't use Firefox so I haven't tested the extension with it very much.

**Comment by GaryJones** [comment]
> For those diff sections that highlighting doesn't work, do they have the toggle diff button to the right?

No.

> Also, if you click the "Show more lines" button, are the newly loaded lines highlighted?

No.




> are you using Chrome or Firefox by the way

Chrome.

I can't even find active references to main.js and prism.js on pages that are highlighted.

**Comment by reyronald** [comment]
Prism.js is bundled inside main.js. It's not a separated file.

> I can't even find active references to main.js and prism.js on pages that are highlighted.

It wouldn't be very useful anyway because all the production code is uglified :/

I'll keep an eye open to see if this ever happens to me

**Comment by reyronald** [comment]
Closing until we can get more information on the issue. If anyone finds out anything let me know.

**Pull request closed without merging**
